groups:
  - id: deployment
    prefix: deployment
    brief: >
      ソフトウェアのデプロイ
    attributes:
      - id: environment
        type: string
        brief: >
          [デプロイ環境](https://en.wikipedia.org/wiki/Deployment_environment)の名前(別名:配置層)
        examples: ['staging', 'production']
